# Generated by Django 3.0.8 on 2020-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('sale_datestart', models.DateTimeField(verbose_name='Дата начала')),
                ('sale_dateend', models.DateTimeField(verbose_name='Дата конца')),
                ('sale_description', models.TextField(verbose_name='Описание')),
                ('sale_image', models.ImageField(upload_to='')),
                ('sale_service', models.ManyToManyField(to='services.Service')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
