# Generated by Django 3.0.8 on 2020-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200919_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CashOrCard',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
