# Generated by Django 3.0.8 on 2020-09-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200921_1630'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('order_time', models.TimeField(verbose_name='Время заказа')),
                ('order_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя(если не зарегстрирован)')),
                ('order_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail(если не зарегстрирован)')),
                ('order_telephonenumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон(если не зарегстрирован)')),
                ('order_state', models.CharField(max_length=100, verbose_name='Статус заказа')),
                ('order_address', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('CashOrCard', models.BooleanField(blank=True, null=True)),
                ('order_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('order_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Worker')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.Service')),
            ],
        ),
    ]
