# Generated by Django 3.0.8 on 2020-09-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100, verbose_name='ФИО Работника')),
                ('worker_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('worker_password', models.CharField(max_length=200, verbose_name='Пароль Работника')),
                ('worker_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('worker_birthdaydate', models.DateField(verbose_name='Дата рождения')),
                ('worker_image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('client_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('client_birthdaydate', models.DateField(verbose_name='Дата рождения')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
