# Generated by Django 3.0.8 on 2020-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_password',
            field=models.CharField(default='client', max_length=200, verbose_name='Пароль клиента'),
            preserve_default=False,
        ),
    ]
