# Generated by Django 3.0.8 on 2020-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainservice_name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('mainservice_description', models.TextField(verbose_name='Описание раздела')),
                ('mainservice_images', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
